'use strict';
let a = +prompt('Число "a"', 2);
let b = +prompt('Число "b"', 3);
const addition = a + b;
console.log('Addition:', addition);
const subtraction = a - b;
console.log('Subtraction:', subtraction);
const multiplication = a * b;
console.log('Multiplication:', multiplication);
const division = a / b;
console.log('Division:', division);