'use strict';
let a = +prompt('Число "a"', '2');
let b = +prompt('Число "b"', '3');
const addition = a + b;
const subtraction = a - b;
const multiplication = a * b;
const division = a / b;
console.log('Addition:', addition);
console.log('Subtraction:', subtraction);
console.log('Multiplication:', multiplication);
console.log('Division:', division);